version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: ${NODE_ENV}
    command: yarn start:dev api
    env_file:
      - ./apps/api/.env
    ports:
      - 4000:4000
    volumes:
      - ./apps/api:/usr/src/app/apps/api:z
      - ./libs/common:/usr/src/app/libs/common:z
      - ./public:/usr/src/app/public:z
    depends_on:
      - nats

  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: ${NODE_ENV}
    command: yarn start:dev users
    env_file:
      - ./.env
      - ./apps/users/.env
    volumes:
      - ./apps/users:/usr/src/app/apps/users:z
      - ./libs/common:/usr/src/app/libs/common:z
    depends_on:
      - nats

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: ${NODE_ENV}
    command: yarn start:dev payments
    env_file:
      - ./.env
      - ./apps/payments/.env
    volumes:
      - ./apps/payments:/usr/src/app/apps/payments:z
      - ./libs/common:/usr/src/app/libs/common:z
    depends_on:
      - nats

  posts:
    build:
      context: .
      dockerfile: ./apps/posts/Dockerfile
      target: ${NODE_ENV}
    command: yarn start:dev posts
    env_file:
      - ./.env
      - ./apps/posts/.env
    volumes:
      - ./apps/posts:/usr/src/app/apps/posts:z
      - ./libs/common:/usr/src/app/libs/common:z
    depends_on:
      - nats

  videos:
    build:
      context: .
      dockerfile: ./apps/videos/Dockerfile
      target: ${NODE_ENV}
    command: yarn start:dev videos
    env_file:
      - ./.env
      - ./apps/videos/.env
    volumes:
      - ./apps/videos:/usr/src/app/apps/videos:z
      - ./libs/common:/usr/src/app/libs/common:z
    depends_on:
      - nats

  history:
    build:
      context: .
      dockerfile: ./apps/history/Dockerfile
      target: ${NODE_ENV}
    command: yarn start:dev history
    env_file:
      - ./.env
      - ./apps/history/.env
    volumes:
      - ./apps/history:/usr/src/app/apps/history:z
      - ./libs/common:/usr/src/app/libs/common:z
    depends_on:
      - nats

  storage:
    build:
      context: .
      dockerfile: ./apps/storage/Dockerfile
      target: ${NODE_ENV}
    command: yarn start:dev storage
    env_file:
      - ./.env
      - ./apps/storage/.env
    ports:
      - 4001:80
    volumes:
      - ./apps/storage:/usr/src/app/apps/storage:z
      - ./libs/common:/usr/src/app/libs/common:z
      - ./public:/usr/src/app/public:z
    depends_on:
      - nats

  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
