apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: ocir-registry-secret-seoul
      containers:
        - name: api
          image: ap-seoul-1.ocir.io/cnqphqevfxnp/development-api:0.8
          env:
            - name: 'SERVICE_NAME'
              value: 'api'
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  type: ClusterIP # Network Load Balancer(L4) 적용 시 NodePort 사용, ingress-nginx(L4, L7) 적용 시 ClusterIP 가능
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
