apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      imagePullSecrets:
        - name: ocir-registry-secret
      containers:
        - name: payments
<<<<<<< HEAD
          image: ap-seoul-1.ocir.io/cnqphqevfxnp/development-payments:0.85
=======
          image: ap-seoul-1.ocir.io/cnqphqevfxnp/development-payments:0.105
>>>>>>> 3e7095ee4c3f2c19afdc122225ed0403d39cf4ec
          env:
            - name: 'SERVICE_NAME'
              value: 'payments'
---
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  selector:
    app: payments
  type: ClusterIP # Network Load Balancer(L4) 적용 시 NodePort 사용, ingress-nginx(L4, L7) 적용 시 ClusterIP 가능