apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      imagePullSecrets:
        - name: ocir-registry-secret-seoul
      containers:
        - name: posts
<<<<<<< HEAD
          image: ap-seoul-1.ocir.io/cnqphqevfxnp/development-posts:0.8
=======
          image: ap-seoul-1.ocir.io/cnqphqevfxnp/development-posts:0.8
>>>>>>> 3e7095ee4c3f2c19afdc122225ed0403d39cf4ec
          env:
            - name: 'SERVICE_NAME'
              value: 'posts'
---
apiVersion: v1
kind: Service
metadata:
  name: posts
spec:
  selector:
    app: posts
  type: ClusterIP # Network Load Balancer(L4) 적용 시 NodePort 사용, ingress-nginx(L4, L7) 적용 시 ClusterIP 가능
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
