apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
spec:
  replicas: 2
  selector:
    matchLabels:
      app: history
  template:
    metadata:
      labels:
        app: history
    spec:
      imagePullSecrets:
        - name: ocir-registry-secret
      containers:
        - name: history
          image: ap-seoul-1.ocir.io/cnqphqevfxnp/production-history:latest
          env:
            - name: 'SERVICE_NAME'
              value: 'history'
---
apiVersion: v1
kind: Service
metadata:
  name: history
spec:
  selector:
    app: history
  type: ClusterIP # Network Load Balancer(L4) 적용 시 NodePort 사용, ingress-nginx(L4, L7) 적용 시 ClusterIP 가능
